### ISSUE TITLE
Migrate UI components from AngularJS to React

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#1007]
_This is a large subtask of https://github.com/hypothesis/client/issues/972._

The largest part of the migration from AngularJS to React will be to convert our existing UI components in `src/sidebar/components` and their associated tests. Along the way we will probably want to refactor some of the larger components into smaller ones, both to ease the conversion effort and to make the resulting code more maintainable.

**Initial tasks:**

- [x] Add tooling and dependencies to our project so we can write React components, tests for them and use a linter to catch common bugs (https://github.com/hypothesis/client/pull/1027)
- [x] Add a bridge to allow AngularJS templates to include components that are implemented in React (https://github.com/hypothesis/client/pull/1027)
- [x] Pick a simple example component at the leaf of the tree and convert it over to prove that everything works (https://github.com/hypothesis/client/pull/1028)

Once we have that working, we can begin to convert the existing component tree, starting at the leaf components and working our way upwards. We're done when the root `<hypothesis-app>` component is converted.

**Components to convert:**

This is the full list of components to convert, taken from `src/sidebar/index.js`. Some of these are small and may only take an hour or two, others (eg. "annotation") are much larger and will need their own issues.

- [x] annotation pre-work: extract sub-components (https://github.com/hypothesis/client/issues/1472)
- [x] annotation (https://github.com/hypothesis/client/issues/1650)
- [x] annotationActionButton
- [x] annotationHeader (https://github.com/hypothesis/client/issues/1200)
- [x] ~~annotationShareDialog~~ (now `AnnotationShareControl`) (https://github.com/hypothesis/client/issues/1201)
- [x] annotationThread
- [x] annotationViewerContent
- ~~[ ] dropdownMenuBtn~~ now part of `annotationPublishControl`
- [x] excerpt (https://github.com/hypothesis/client/issues/1202)
- [x] groupList
- [x] groupListItem
- ~~[x] groupListOutOfScopeItem~~ (No longer a standalone component)
- [x] groupListSection
- [x] helpLink
- [x] helpPanel (https://github.com/hypothesis/client/issues/1203)
- [x] hypothesisApp
- [x] loggedoutMessage (https://github.com/hypothesis/client/issues/1204)
- [x] loginControl (slated for removal: https://github.com/hypothesis/client/issues/1205, removed in https://github.com/hypothesis/client/issues/1007)
- [x] markdown (https://github.com/hypothesis/client/issues/1424)
- [x] moderationBanner (https://github.com/hypothesis/client/pull/1198)
- [x] newNoteBtn (https://github.com/hypothesis/client/issues/1206)
- [x] publishAnnotationBtn (refactored and renamed `annotationPublishControl`)
- [x] searchInput
- [x] searchStatusBar (https://github.com/hypothesis/client/issues/1207)
- [x] selectionTabs (https://github.com/hypothesis/client/issues/1208)
- [x] shareDialog (https://github.com/hypothesis/client/issues/1209)
- [x] sidebarContent
- [x] sidebarTutorial (a plan of action is being discussed in https://github.com/hypothesis/product-backlog/issues/1031)
- [x] sortDropdown
- [x] spinner
- [x] streamContent
- [x] svgIcon
- [x] tagEditor (https://github.com/hypothesis/client/issues/1210)
- [x] threadList
- [x] timestamp
- [x] topBar (https://github.com/hypothesis/client/pull/1184)

**Comment by robertknight** [comment]
All done as of https://github.com/hypothesis/client/issues/2096.
