### ISSUE TITLE
Migrate Excerpt Component to Preact

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1202]
This component has some complexity to it and will need a preview by @robertknight 

----

- [x] Convert excerpt to Preact
- [x] Investigate regression in https://github.com/hypothesis/client/issues/1518
- [x] Follow up on the cleanup tasks in [this comment](https://github.com/hypothesis/client/issues/1202#issuecomment-556042566) (https://github.com/hypothesis/client/pull/1546)
- [x] ~~Decide whether to do anything about the performance issues found in [this issue](https://github.com/hypothesis/client/issues/1517)~~ (_I'm going to leave this for now since the issue will be resolved automatically when the parent annotation list is converted_ - @robertknight)

**Comment by robertknight** [comment]
I've started working on this. Some discoveries along the way:

1. The `<excerpt>` component renders children that are passed to it. The Angular <-> Preact bridge doesn't support this, and it is difficult to add support, which means we need to convert the parts of the `annotation.html` template at the same time.
2. The `<excerpt>` implementation and API would benefit from being restructured and simplified somewhat

**Comment by robertknight** [comment]
The bulk of this is done. There are a few cleanup tasks I identified:

- See if the `hasContent` prop can be removed from `AnnotationBody`. We might be able to infer it from the `text` prop
- Move the `annotation-body` and `annotation-quote` styles to their own SASS files to follow our conventions in the app
