### ISSUE TITLE
Fix UX bugs related to expanding and collapsing parts of threads, when the client is filtered

### ISSUE THREAD

**Issue by seanh** [hypothesis/client#1243]
When a search filter is applied in the client and some of the matches are replies in threads (possibly nested multiple levels deep) there are some bugs involving expanding and collapsing parts of threads while a search filter is applied. Identify issues and fix them.

**Comment by klemay** [comment]
These issues have been identified as:

- [ ] [Annotations disappear on save if there is a search filter active](https://github.com/hypothesis/client/issues/10)
- [ ] [reply editor hidden when sidebar search in effect](https://github.com/hypothesis/client/issues/672)
- [ ] [replying to an annotation in search results hides the reply](https://github.com/hypothesis/client/issues/690)
- [ ] [When focused on a user, there is no way to re-hide replies from another user](https://github.com/hypothesis/client/issues/1383)
- [ ] [Distinguish matching and non-matching annotations and replies when the sidebar is filtered](https://github.com/hypothesis/client/issues/1242)
