### ISSUE TITLE
Prepare for `Annotation` Angular component migration

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1472]
To prepare for the migration of the hefty `Annotation` component from Angular to preact, we should extract out some sub-components and factor out some complexity from the existing controller. This will make the migration of both the UI component and some business logic later more straightforward.

This is primarily a refactoring task, so rigorous organization is not helpful as the following list may morph, but it can serve as a high-level guide:

## Potential Annotation Sub-Components

- [ ] AnnotationFooter sub-components
	- [x] AnnotationActionBar
	- [x] AnnotationLicense
	- [ ] AnnotationReplyControl
- [ ] Annotation body
	- [ ] TagView
	- [x] Integrate TagEditor
	- [ ] Collapse controls

## Potential Simplifications of Annotation Controller

- [x] Factor out analytics tracking
- [ ] Remove simple wrapper attribute methods (e.g. `this.group`, `this.isShared`)
- [ ] Look at collapsing-related methods for possible simplification/refactor

## Etc.

- [ ] Meet and establish consensus of plan to migrate remaining `Annotation` logic

**Comment by lyzadanger** [comment]
Closing this as resolved as we are now moving into `Annotation` migration proper, so "prep" is thus done, as such.
