### ISSUE TITLE
Migrate Annotation component to preact

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#1650]
Part of https://github.com/hypothesis/client/issues/1007

This epic is to track the conversion of the `Annotation` component to preact. It is a complex component, so migration will occur over several steps.

At time of writing, the plan is to:

* Build up the new `Annotation2020` (or whatever working title we use) next to the existing `Annotation` component.
* [x] Establish a feature flag so that interested parties may view the new `Annotation` component during development
* Continue to whittle down existing logic in `Annotation` to make the overall component smaller.

### `Annotation` migration checklist

Check off when these sub-components and features are supported in the "new" `AnnotationOmega` component:

* [x] Save-on-keystroke (https://github.com/hypothesis/client/issues/1838) — you can save an annotation, when editing, by typing "CMD-Enter" (Mac) or "CTRL-Enter" (Everyone else)
* [x] Error-handling when user not logged in (https://github.com/hypothesis/client/pull/1813)
* [x] `AnnotationHeader` (User, timestamp, group information at top of annotation card)
* [x] `AnnotationQuote` (Excerpted bit, in italic, of highlighted text)
* [x] `AnnotationBody` - The actual content of the annotation
* [x] `TagEditor` 
* [x] `TagList` — The annotation tags, which you see when not in editing mode
* [x] `AnnotationPublishControl` (render only/no saving)
* [x] Handle when user changes privacy level of the annotation (from within the publish controls, i.e. "Publish to (group)" or "Only Me")
* [x] `AnnotationLicense` - The license text that renders at the bottom of the editor when the annotation is public
* [x] Reply thread expand/collapse - Expanding and collapsing replies and nested replies
* [x] `AnnotationActionBar` — the various controls, including reply, flag, delete, share
* [x] CRUD implementation: `save` (This means that saving an annotation actually works)
* [x] save-new-highlight automatically (https://github.com/hypothesis/client/issues/1833) — new highlights are automatically saved
* [x] enter edit mode — the annotation card enters "edit" mode when first created, when edited, when a reply is created
* [x] create reply logic — clicking "reply" creates an empty reply in the correct spot
* [x] revert edits — canceling out of an edit session puts things back as you'd expect
* [x] ~~annotation hover styling (https://github.com/hypothesis/client/issues/1835)~~ This is on `AnnotationThread`, not `Annotation`
* [x] externalize annotation-draft creation (https://github.com/hypothesis/client/issues/1834) — the creation of a draft (i.e. what puts the annotation in editing mode) happens outside of the component, not within it (this is not a user-visible change)
* [x] handle "isSaving" state (https://github.com/hypothesis/client/issues/1836) (render a "Saving..." message when the annotation is actively saving)
* [x] classes/display, etc., for collapsed or hidden annotations or threads — collapsing, expanding, filtering annotations and replies should show the correct things within an annotation card (https://github.com/hypothesis/client/issues/1837)
* ~~flash errors, a11y of same, etc. — i.e. how best to present errors to user?~~ Tracked elsewhere

**Comment by lyzadanger** [comment]
As of https://github.com/hypothesis/client/commit/8142037e518c5b3158148f915752b6a9d70683b7 the migration implementation tasks are complete.

`AnnotationOmega` (i.e. the new annotation component) remains behind a feature flag until QA is complete. The only intentional difference between the legacy `Annotation` and `AnnotationOmega` is a disclaimer at the top of each `AnnotationOmega` that says: "Viewing AnnotationOmega" — that way, it's easy to tell that the feature flag is switched on.

Once QA is complete and we're ready to turn on the new `AnnotationOmega` for everyone, we'll want to go through the tasks outlined in https://github.com/hypothesis/client/issues/1867 to wrap up the migration project and clean up.
