### ISSUE TITLE
Create packages of common code between front-end applications

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2181]
This issue is a placeholder/starting point for a project to package up reusable, shared (JavaScript) code between Hypothesis front-end applications. Examples include things like: RPC functionality, common preact components like SvgIcons.

### Minimal  working feature includes

- [ ]  Separate workspace (yarn or otherwise) nested under the client repo (possibly at the root level)
- [ ]  The work space should contain some minimal css or mixins that are intended to be shared with LMS from the outset. Use existing LMS css UX bugs to target candidate css/mixins that could be shared initially.
- [ ]  Mixins should be importable directly back into the client app (e.g. don't break anything) & syntax errors should still report as normal.
- [ ]  Workspace needs to be able to be packaged up and uploaded as an npm module. This can be manually for now, and we can explore automation later.
- [ ]  npm module shall be able to be downloaded in the LMS frontend package installer and mixins should be importable in modules that need them.

### Future updates may include

-  Build this with the intent to eventually include js and svg resources, but these don't have to work from the outset.
- The existing client file structure may eventually need some reorganization with the idea that shared things go into this subfolder. 
- Only things that are actually shared and used in 2 or more places should go here.

**Comment by robertknight** [comment]
I believe all the items in this task are now done. The package lives in the https://github.com/hypothesis/frontend-shared repo.
