### ISSUE TITLE
Implement agreed-upon CSS/design-application conventions in client

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/client#2245]
This is an informal epic to track the work discussed in the developer offsite pertaining to applied design in the client (specifically the sidebar). The work discussed there dovetails into/leads off of a couple of the engineering DOs for Q2 and will likely also be reflected as DOs for Q3. See [the presentation slides](https://docs.google.com/presentation/d/1KaybBD_bhtVCREtCC1ZOtJcZIr3xLGCExHEP9QyVZZs/edit?usp=sharing) (requires Hypothesis Google team access) for justification and explanation.

In the presentation, the work is broken down into roughly 6 steps, though there are some known (and some unknown) follow-up that will be needed:

1. [x] Remove unnecessary style rules
2. [x] Extract some basic layout mixins
3. [x] Extract some atomic helpers (borders, etc.)
4. [x] Extract "molecules" (reusable, more sophisticated patterns)
5. [x] Implement appropriate utility classes
6. [x] Consolidate, cleanup, repeat
7. [x] Update our documentation on conventions

**Comment by lyzadanger** [comment]
This stage of this project is complete!
