### ISSUE TITLE
Convert remaining coffee script files to js modules/ preact components

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#2340]
This is tracking the work effectively needed in `/src/annotator`

`/src/annotator/anchoring/`

- [x] html.coffee
- [x] range.coffee
- [x] types.coffee
- [x] util.coffee
- [x] xpath.coffee

`/src/annotator/plugin/`

- [x] bucket-bar.coffee
- [x] cross-frame.coffee
- [x] pdf.coffee

`/src/annotator/`

- [x] delegator.coffee
- [x] guest.coffee
- [x] host.coffee
- [x] ~~plugin.coffee~~ eliminated
- [x] sidebar.coffee

`/src/annotator/test/`

- [x] guest-test.coffee
- [x] host-test.coffee
- [x] sidebar-test.coffee

There are a number of tools to convert from coffee to js files, but likely nothing that does not require some manual intervention. We could perhaps rely on some of these tools as a rough start, and then polish up the conversions by hand. It's also worth taking a look at the overall layout and organization of the /annotator as now may be a good time to do some lightweight renaming / refactoring -- although, we should steer clear of heavy refactoring until everything is converted as it will be easier to do that in a second pass.

Some conversions have already been done, its worth following previous examples 
https://github.com/hypothesis/client/issues?q=label%3ADecaffeination+
