### ISSUE TITLE
Move frontend-shared to its own repository. 

### ISSUE THREAD

**Issue by LMS007** [hypothesis/client#3017]
Keeping these packages coupled leads to more confusion and issues than keeping them separate. They are truly intended to be decoupled so having independent releases and workflows makes more sense.

The package will need to 

- [x] - execute its own github action to release to npmjs
- [x] - create its own changelog for github releases
- [x] - transpile its own code into /lib
- [x] - lint & formatting
- [x] - codecov (https://github.com/hypothesis/frontend-shared/pull/14)
- [x] - typecheck itself
- [x] - unit testing
- [x] - unit testing w/ grep
- [x] - accessibility testing checks & css bundling into unit tests
- [ ] - launch its own server to render a live pattern lib (https://github.com/hypothesis/client/issues/3015)
- [x] - mockable-imports (testing) (https://github.com/hypothesis/frontend-shared/pull/14)

**Comment by robertknight** [comment]
I'm going to close out this issue as done. The package has been moved to https://github.com/hypothesis/frontend-shared and testing, CI, deployment etc. has all been set up. The only remaining task was to set up some kind of dev server for it. I think that's beyond the core scope of this issue though and we can iterate on that as a separate task.
