### ISSUE TITLE
Epic: overhaul the inter-frame communication system

### ISSUE THREAD

**Issue by esanzgar** [hypothesis/client#3533]
After a full examination of the inter-frame communication system, we proposed a plan with different options #3403. We decided to go ahead and evaluate the option of using `MessageChannel` API.

These are the steps I envision next:
- [x] create a working prototype of the `notebook` <-> `sidebar` communication (#3494).
- [x] to the previous prototype, add `host` <-> `sidebar` communication (fixes the multi-frame test) (#3537).
- [x] to the previous prototype, add `guest` <-> `sidebar` communication (fixes the EPUB related tests) (#3534). 
- [x] create a design document https://docs.google.com/document/d/1Y_PWj_0dPjWJhnCnoM21xyujqWKPVzvu4toEynqqYaI/edit?ts=60ddf16c# 
- [x]  support `MessageChannel` in `FrameRPC` (https://github.com/hypothesis/client/pull/3565) `Bridge` (https://github.com/hypothesis/client/pull/3566) classes.
- [x]  decouple `CrossFrame` from `Guest`, `FrameObserver` from `CrossFrame`, and review the relation between `CrossFrame` and `AnnotationSync`. This will help to separate the communication functionality from unrelated functionality.
- [x]  implement `PortProvider` and `PortFinder`. (https://github.com/hypothesis/client/pull/3881/)
- [x] support `MessageChannel` on other communication related classes, like `CrossFrame` and `FrameSync`.
- [x] enable the new communication system without removing the code for the old communication one, so we can roll back easily in case of unexpected issues.
- [x] if everything goes well, after a cool down period, remove deprecated classes (`Discovery`) and methods.

Other steps we could take in the future could be:
- [ ] cleanup, consolidation or removal of AnnotationSync, or Bridge.
- [ ]  use JSON-RPC for all the `postMessage` communication.
- [ ] replace current `lms` <-> `sidebar` communication.
