### ISSUE TITLE
Migrate Hypothesis client away from AngularJS

### ISSUE THREAD

**Issue by robertknight** [hypothesis/client#972]
The bulk of the logic and UI in the Hypothesis client is in the application which runs in an iframe in the sidebar. This is built with AngularJS (aka. Angular v1). For a variety of reasons, this is getting in the way of current and future development work and we want to migrate away from it. These include:

- Documentation: The documentation is poor, compared to eg. React or Vue. This makes it difficult for new and existing developers to learn to contribute to the client. Additionally AngularJS predates various aspects of the modern web platform (modules, promises, fetch) and so has its own versions of those which developers have to learn as well.
- Performance: AngularJS is our largest dependency, ~220KB of minified JS, and we want to reduce the overall script size of the client.
- Tooling: The tooling (linting, code formatting, error handling, performance analysis, browser dev tools) is much better for more modern frameworks/UI libraries
- Ecosystem: AngularJS is no longer being developed upstream. This is not an immediate technical problem since browsers won't "drop support" for running AngularJS apps, but the dwindling mindshare is a problem for hiring, finding pre-built solutions for problems. Potential contributors are also more likely to have used React, Vue etc.
- Consistency across Hypothesis front-end projects: We're about to start building richer front-end apps for other projects (eg. LMS integration), and it would be helpful to have a standard frontend toolkit for this. We don't want to use AngularJS for that.

## Goals

- Make it easier for new and existing developers to write UI and UI tests for the client
- Reduce the JavaScript bundle size of the client, so that it starts up faster, especially on lower-end devices
- Make it easier to re-use parts of the client in other applications. For example, the Hypothesis API client and components for annotation cards.
- Establish a standard set of tools for building rich client-side UI which we can use in other projects, so developers can easily move between one project and another

## Migration plan

We are going to replace AngularJS in the client with a mixture of web platform features, standalone libraries and a more modern UI library. The current plan is to go with React or a React-like library. It ticks the boxes above and several team members have previous experience with it.

- [x] Replace Angular for UI components with React (or a React-like library) (https://github.com/hypothesis/client/issues/1007)
- [x] Remove remaining use of Angular events for service <-> UI communication (https://github.com/hypothesis/client/issues/1994)
- [x] Replace Angular's AJAX service (`$http`) with `fetch` (
https://github.com/hypothesis/client/issues/974)
- [x] Replace angular-sanitize with a standalone HTML sanitization library (this is security-sensitive, DOMPurify looks like the most promising option) (
https://github.com/hypothesis/client/issues/975)
- [x] Replace Angular's promise service (`$q`) with JS promises (
https://github.com/hypothesis/client/issues/974)
- [x] Replace Angulartics with either direct usage of Google Analytics client library or a suitable wrapper of it (
https://github.com/hypothesis/client/issues/976)
- [x] Figure out a replacement for AngularJS's dependency injection system (https://github.com/hypothesis/client/issues/979)
- [x] Replace uses of Angular utility functions (`angular.{copy, extend, isDefined, isFunction, isNumber, noop}`) with vanilla JS (https://github.com/hypothesis/client/issues/977)
- [x] Replace angular-route with an alternate method for changing app content depending on URL (https://github.com/hypothesis/client/issues/1878)
- [x] Replace angular-toastr with a better looking and more accessible UI (almost done, final part in https://github.com/hypothesis/client/pull/2094)

## Post-migration cleanup

- [x] Stop bundling AngularJS with the client and remove it from the client's dependencies
- [x] Audit the client code for any remaining references to Angular and fix them up
- [x] Close any old issues which are not relevant after this migration

**Comment by lyzadanger** [comment]
@robertknight We ready to close this bad boy?

**Comment by robertknight** [comment]
Yes, we're done with this now.
